# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 141a83d9f522e1b602029ea7c576a9254454f0f68ec2d1e4737b3250c1109d52fc37a4ed92d6e23b9d726763e568043aab597974abed92fbd13028dd8e03858b

test:
  secret_key_base: d56a8e53881a6bb24df4eeb22408e8028bb8204c59cab05628b84fdbf2cd68387adb03274022adb3f306d57a815417a3a3ca28d3d312b4023b27297de3d5f421

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
