json.call(
        user,
        :id,
        :email,
        :first_name,
        :last_name,
        :username,
        :image_file_file_name,
        :image_file_content_type,
        :image_file_file_size
    )
